-- Create Indexes
CREATE UNIQUE INDEX actor_pkey ON public.actor USING btree (actor_id);
CREATE UNIQUE INDEX address_pkey ON public.address USING btree (address_id);
CREATE UNIQUE INDEX category_pkey ON public.category USING btree (category_id);
CREATE UNIQUE INDEX city_pkey ON public.city USING btree (city_id);
CREATE UNIQUE INDEX country_pkey ON public.country USING btree (country_id);
CREATE UNIQUE INDEX customer_pkey ON public.customer USING btree (customer_id);
CREATE UNIQUE INDEX film_actor_pkey ON public.film_actor USING btree (actor_id, film_id);
CREATE UNIQUE INDEX film_category_pkey ON public.film_category USING btree (film_id, category_id);
CREATE UNIQUE INDEX film_pkey ON public.film USING btree (film_id);
CREATE UNIQUE INDEX inventory_pkey ON public.inventory USING btree (inventory_id);
CREATE UNIQUE INDEX language_pkey ON public.language USING btree (language_id);
CREATE UNIQUE INDEX payment_pkey ON public.payment USING btree (payment_id);
CREATE UNIQUE INDEX rental_pkey ON public.rental USING btree (rental_id);
CREATE UNIQUE INDEX staff_pkey ON public.staff USING btree (staff_id);
CREATE UNIQUE INDEX store_pkey ON public.store USING btree (store_id);
CREATE INDEX film_fulltext_idx ON public.film USING gist (fulltext);
CREATE INDEX idx_actor_last_name ON public.actor USING btree (last_name);
CREATE INDEX idx_fk_address_id ON public.customer USING btree (address_id);
CREATE INDEX idx_fk_city_id ON public.address USING btree (city_id);
CREATE INDEX idx_fk_country_id ON public.city USING btree (country_id);
CREATE INDEX idx_fk_customer_id ON public.payment USING btree (customer_id);
CREATE INDEX idx_fk_film_id ON public.film_actor USING btree (film_id);
CREATE INDEX idx_fk_inventory_id ON public.rental USING btree (inventory_id);
CREATE INDEX idx_fk_language_id ON public.film USING btree (language_id);
CREATE INDEX idx_fk_rental_id ON public.payment USING btree (rental_id);
CREATE INDEX idx_fk_staff_id ON public.payment USING btree (staff_id);
CREATE INDEX idx_fk_store_id ON public.customer USING btree (store_id);
CREATE INDEX idx_last_name ON public.customer USING btree (last_name);
CREATE INDEX idx_store_id_film_id ON public.inventory USING btree (store_id, film_id);
CREATE INDEX idx_title ON public.film USING btree (title);
CREATE UNIQUE INDEX idx_unq_manager_staff_id ON public.store USING btree (manager_staff_id);
CREATE UNIQUE INDEX idx_unq_rental_rental_date_inventory_id_customer_id ON public.rental USING btree (rental_date, inventory_id, customer_id);
CREATE INDEX idx_release_year ON public.film(release_year);
CREATE INDEX idx_title_release_year ON public.film USING btree (title, release_year);
CREATE INDEX idx_customer_rental_date ON public.rental USING btree (customer_id, rental_date);
